### ISSUE TITLE
Add spectral band bounds info to the transmission spectrum calculation

### ISSUE THREAD

**Issue by mzamyatina** [exoclim/aeolus#46]
Would be nice to keep the information about the width of spectral bands used in transmission spectrum calculations.
Currently this information is lost in places like [this](https://github.com/exoclim/aeolus/blob/main/src/aeolus/synthobs.py#L183).

**Comment by dennissergeev** [comment]
Added by 7df178cb6af510e9124c30c12215c22f16aceb8d

Upper and lower band limits are now stored as auxiliary coordinates, as shown at the end of [this example notebook](https://exoclim.github.io/aeolus/examples/03_Transmission_Spectrum.html).
